// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.3
// source: grpc-exercises/ex5-doublestream/proto/double.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type HiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId   string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestData string `protobuf:"bytes,2,opt,name=requestData,proto3" json:"requestData,omitempty"`
}

func (x *HiRequest) Reset() {
	*x = HiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_exercises_ex5_doublestream_proto_double_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiRequest) ProtoMessage() {}

func (x *HiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exercises_ex5_doublestream_proto_double_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiRequest.ProtoReflect.Descriptor instead.
func (*HiRequest) Descriptor() ([]byte, []int) {
	return file_grpc_exercises_ex5_doublestream_proto_double_proto_rawDescGZIP(), []int{0}
}

func (x *HiRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HiRequest) GetRequestData() string {
	if x != nil {
		return x.RequestData
	}
	return ""
}

type HiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	IsSuccess bool   `protobuf:"varint,2,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	Result    string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *HiResponse) Reset() {
	*x = HiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_exercises_ex5_doublestream_proto_double_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiResponse) ProtoMessage() {}

func (x *HiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exercises_ex5_doublestream_proto_double_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiResponse.ProtoReflect.Descriptor instead.
func (*HiResponse) Descriptor() ([]byte, []int) {
	return file_grpc_exercises_ex5_doublestream_proto_double_proto_rawDescGZIP(), []int{1}
}

func (x *HiResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *HiResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *HiResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_grpc_exercises_ex5_doublestream_proto_double_proto protoreflect.FileDescriptor

var file_grpc_exercises_ex5_doublestream_proto_double_proto_rawDesc = []byte{
	0x0a, 0x32, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x73,
	0x2f, 0x65, 0x78, 0x35, 0x2d, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x09, 0x48,
	0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x56, 0x0a, 0x0a, 0x48, 0x69, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69,
	0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0x42, 0x0a, 0x09, 0x48, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a,
	0x0a, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_exercises_ex5_doublestream_proto_double_proto_rawDescOnce sync.Once
	file_grpc_exercises_ex5_doublestream_proto_double_proto_rawDescData = file_grpc_exercises_ex5_doublestream_proto_double_proto_rawDesc
)

func file_grpc_exercises_ex5_doublestream_proto_double_proto_rawDescGZIP() []byte {
	file_grpc_exercises_ex5_doublestream_proto_double_proto_rawDescOnce.Do(func() {
		file_grpc_exercises_ex5_doublestream_proto_double_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_exercises_ex5_doublestream_proto_double_proto_rawDescData)
	})
	return file_grpc_exercises_ex5_doublestream_proto_double_proto_rawDescData
}

var file_grpc_exercises_ex5_doublestream_proto_double_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_exercises_ex5_doublestream_proto_double_proto_goTypes = []interface{}{
	(*HiRequest)(nil),  // 0: proto.HiRequest
	(*HiResponse)(nil), // 1: proto.HiResponse
}
var file_grpc_exercises_ex5_doublestream_proto_double_proto_depIdxs = []int32{
	0, // 0: proto.HiService.SendStream:input_type -> proto.HiRequest
	1, // 1: proto.HiService.SendStream:output_type -> proto.HiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_exercises_ex5_doublestream_proto_double_proto_init() }
func file_grpc_exercises_ex5_doublestream_proto_double_proto_init() {
	if File_grpc_exercises_ex5_doublestream_proto_double_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_exercises_ex5_doublestream_proto_double_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_exercises_ex5_doublestream_proto_double_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_exercises_ex5_doublestream_proto_double_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_exercises_ex5_doublestream_proto_double_proto_goTypes,
		DependencyIndexes: file_grpc_exercises_ex5_doublestream_proto_double_proto_depIdxs,
		MessageInfos:      file_grpc_exercises_ex5_doublestream_proto_double_proto_msgTypes,
	}.Build()
	File_grpc_exercises_ex5_doublestream_proto_double_proto = out.File
	file_grpc_exercises_ex5_doublestream_proto_double_proto_rawDesc = nil
	file_grpc_exercises_ex5_doublestream_proto_double_proto_goTypes = nil
	file_grpc_exercises_ex5_doublestream_proto_double_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HiServiceClient is the client API for HiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HiServiceClient interface {
	SendStream(ctx context.Context, opts ...grpc.CallOption) (HiService_SendStreamClient, error)
}

type hiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHiServiceClient(cc grpc.ClientConnInterface) HiServiceClient {
	return &hiServiceClient{cc}
}

func (c *hiServiceClient) SendStream(ctx context.Context, opts ...grpc.CallOption) (HiService_SendStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HiService_serviceDesc.Streams[0], "/proto.HiService/SendStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &hiServiceSendStreamClient{stream}
	return x, nil
}

type HiService_SendStreamClient interface {
	Send(*HiRequest) error
	Recv() (*HiResponse, error)
	grpc.ClientStream
}

type hiServiceSendStreamClient struct {
	grpc.ClientStream
}

func (x *hiServiceSendStreamClient) Send(m *HiRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hiServiceSendStreamClient) Recv() (*HiResponse, error) {
	m := new(HiResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HiServiceServer is the server API for HiService service.
type HiServiceServer interface {
	SendStream(HiService_SendStreamServer) error
}

// UnimplementedHiServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHiServiceServer struct {
}

func (*UnimplementedHiServiceServer) SendStream(HiService_SendStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SendStream not implemented")
}

func RegisterHiServiceServer(s *grpc.Server, srv HiServiceServer) {
	s.RegisterService(&_HiService_serviceDesc, srv)
}

func _HiService_SendStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HiServiceServer).SendStream(&hiServiceSendStreamServer{stream})
}

type HiService_SendStreamServer interface {
	Send(*HiResponse) error
	Recv() (*HiRequest, error)
	grpc.ServerStream
}

type hiServiceSendStreamServer struct {
	grpc.ServerStream
}

func (x *hiServiceSendStreamServer) Send(m *HiResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hiServiceSendStreamServer) Recv() (*HiRequest, error) {
	m := new(HiRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _HiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HiService",
	HandlerType: (*HiServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendStream",
			Handler:       _HiService_SendStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc-exercises/ex5-doublestream/proto/double.proto",
}
